### ISSUE TITLE
Ability to create new Uplink Profiles

### ISSUE THREAD

**Issue by tkrausjr** [madhukark/nsx-pacific#1]
Feature Request - 

Need the ability to create an NSX Uplink Profile during NSX Installation before we prepare the cluster/hosts for NSX.  Should be able to do this for Edge Uplink Profile and ESXi Host Profiles. Need to be able to specify several things that make up a hostprofile at a minimum.

- Transport VLAN

- Teamings( Can probably start with Default teaming) and specify the Active Uplink.

Using NSX 3.0 for WCP setup. Without this I would have to run playbooks indivudally and then go into NSX create two new profiles and then reference them in the config file and resume running playbooks individually.

**Comment by madhukark** [comment]
Added support to create Uplink Host Switch Profile.

It introduces 2 new configs: Transport_vlan and MTU. Just provide the info in nsx-configs.txt and start the install (nsx-install.py --start).
